@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@json = Content-Type: application/json

@baseUrl = http://{{host}}/user

// get user info
GET {{baseUrl}}/info HTTP/1.1

### 
// login with username and password
POST {{baseUrl}}/login HTTP/1.1
{{json}}

{
    "username": "test",
    "password": "pwd123",
}

### 

POST  {{baseUrl}}/logout HTTP/1.1
{{json}}

{

}

###
PUT {{baseUrl}}/info HTTP/1.1
{{json}}

{

}
