[workspace]
members = [
    "server/micro-service",
    "server/usersvr",
    "server/gateway",
    "server/sessionsvr",
    "server/idsvr",
    "server/sdwp",
    "server/discover",
    "server/testsvr"
]
[profile.release]
lto = true