[workspace]
members = [
    "server/micro-service",
    "server/usersvr",
    "server/gateway",
    "server/sessionsvr",
    "server/idsvr",
    "server/sdwp",
    "server/testsvr",
    "server/containersvr"
]
[profile.release]
lto = true