config: &default-config
  url: /run/docker/containerd/containerd.sock
  containers:
    namespace: test
    base:
      image: alpine:latest
      limit:
        cpu: 100m
        memory: 64m
        io: 100
      runtime: io.containerd.runc.v2
      snapshotter: native
    musl-runner-M0: 
      image: musl:latest
      extends: base

global:
  username: username
  password: password
  pgUrl: postgresql://user:passwd@host:port/db
  image:
    prefix: docker/yourname
    pullSecrets: 
    pullPolicy: Always
  config: 
    <<: *default-config


