[package]
name = "sdwp"
version = "0.1.0"
authors = ["kadds <itmyxyf@gmail.com>"]
edition = "2018"
description = "server debug web page"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2"
actix-web = "4.0.0-beta.3"
anyhow = "1"
thiserror = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "1.0", features = ["full"]}
tonic = "0.4"
prost = "0.7"
log = "0.4"
env_logger = "0.8"
futures = "0.3"
rand = "0.8"
lazy_static = "1"
envy = "0.4"
discover = {path = "../discover"}

[build-dependencies]
tonic-build = "0.4"