[package]
name = "usersvr"
version = "0.1.0"
authors = ["kadds <itmyxyf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.5"
futures = "0.3"
dotenv = "0.15.0"
liblog = { path = "../liblog" }
tokio = { version = "0.2", features = ["full"] }
tonic = "0.2"
log = "0.4"
lazy_static = "1.4"
prost = "0.6"

[build-dependencies]
tonic-build = "0.2"