apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-cfg
  namespace: {{ .Release.Namespace }}
data: 
  JJ_SESSION_KEY: ""
  JJ_DISCOVER_SUFFIX: "{{ .Release.Namespace }}.svc.{{ .Values.cluster  }}"
  RUST_LOG: {{ .Values.logLevel }}
  JJ_CONFIG_FILE: ./config.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
  namespace: {{ .Release.Namespace }}
type: Basic-auth
stringData: 
  username: {{ .Values.global.username }}
  password: {{ .Values.global.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData: 
  url: {{ .Values.global.pgUrl }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-file-cfg
  namespace: {{ .Release.Namespace }}
data: 
  configfile: |
{{ .Values.global.config | toYaml | indent 4 }}

