apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-cfg
  namespace: {{ .Release.Namespace }}
data: 
  JJ_SESSION_KEY: ""
  JJ_DISCOVER_SUFFIX: "{}.{{ .Release.Namespace }}.svc.{{ .Values.cluster  }}"
  RUST_LOG: {{ .Values.logLevel }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
  namespace: {{ .Release.Namespace }}
data: 

