[comm]
log_host = "localhost"
log_port = 10900 # received by agent
log_type = "Tcp" # Tcp or Console

[etcd]
endpoints = ["your_endpoints"]
password = "your_password"
prefix = "your_prefix"
username = "your_username"
