@hostname = localhost
@port = 6550
@host = {{hostname}}:{{port}}
@contentType = Content-Type: application/json

@base = http://{{host}}/

###
POST {{base}}user/login HTTP/1.1
{{contentType}}

{"username": "admin",
"password": "12345678"}

###

GET {{base}}service/list HTTP/1.1
Token: 
{{contentType}}

{}

### 
GET {{base}}service/rpcs HTTP/1.1
Token: 
{{contentType}}

{"module": "usersvr",
"service": "",
"instance": ""}

### 
GET {{base}}service/rpc HTTP/1.1
Token: 
{{contentType}}

{"module": "usersvr",
"service": "user.rpc.UserSvr",
"instance": "test",
"method":"get_user"}

### 
GET {{base}}service/invoke HTTP/1.1
Token: 
{{contentType}}

{"module": "usersvr",
"instance": "test",
"rpc": ".user.rpc.UserSvr.get_user",
"params": {"id": 1}
}
