[package]
name = "server"
version = "0.1.0"
authors = ["kadds <itmyxyf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2"
hyper = "0.13"
diesel = {version = "1.0", features = ["postgres"] }
iron = "0.6"
protobuf = "2.12.0"
router = "0.6"

[build-dependencies]
protoc      = "2.12.0"
protoc-rust = "2.0"
