global:
  image: 
    prefix: docker.io/kadds/
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: 
  username: admin
  password: job-judge123
  pgUrl: postgres://localhost/job-judge
  config: 

service:
  port: 8080
  replicas: 2

resources: 
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 32Mi

logLevel: Info
cluster: cluster.local